version: '3.8'

services:
  db:
    build:
      context: ./server/db
    container_name: finance_db_container
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financedb

volumes:
  pgdata:
